apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-cluster
  namespace: argocd
spec:
  destination:
    namespace: database
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: cluster
      targetRevision: 0.3.1
      helm:
        releaseName: cluster
        valueFiles:
          - $values/apps/cnpg/values.yaml
    - repoURL: https://github.com/Ditmanson/argocluster
      targetRevision: HEAD
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


