apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docs-pvc
  namespace: griz
spec:
  storageClassName: nfs-csi
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

