apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hugoapps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ditmanson/argocluster
    targetRevision: HEAD
    path: hugo
  destination:
    server: https://kubernetes.default.svc
    namespace: hugo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
