# patch.yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-server
    spec:
      containers:
      - name: argocd-server
        image: argoproj/argocd:latest  # Ensure you have the correct image
        args:
          - /usr/local/bin/argocd-server
          - --staticassets
          - /shared/app
          - --redis
          - argocd-redis:6379
          - --insecure
          - --basehref
          - /argocd
          - --rootpath
          - /argocd
        env:
          - name: ARGOCD_MAX_CONCURRENT_LOGIN_REQUESTS_COUNT
            value: "0"

